/* 
 * File:    PowerButton.h
 * Author:  Jack Lambert     <joalambe@ucsc.edu>
 * Project: WCSA_SDP_2022
 *
 * NOTE: CCP3 code originally generated by Microchip Code Configurator (MCC) 
 *       and then further modified by Jack Lambert.
 *       PowerButton implementations were written from scratch.
 * 
 * Created on May 8, 2022, 5:00 PM
 */
//------------------------------------------------------------------------------

#ifndef POWERBUTTON_H
#define	POWERBUTTON_H

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>


//==============================================================================
//--------------------------------- TYPEDEFS -----------------------------------
//==============================================================================
/**
 @Summary
   Defines the values to convert from 16bit to two 8 bit and vice versa

 @Description
   This routine used to get two 8 bit values from 16bit also
   two 8 bit value are combine to get 16bit.
 */
typedef union CCPR3Reg_tag {

    struct {
        uint8_t ccpr3l;
        uint8_t ccpr3h;
    };

    struct {
        uint16_t ccpr3_16Bit;
    };
} CCP3_PERIOD_REG_T;


//==============================================================================
//------------------------------ PUBLIC LIBRARY --------------------------------
//==============================================================================
/**
 * @funct   PowerButton_Init()
 * @param   None
 * @return  None
 * @brief   Initializes the CCP3 (pin[RA2]) to interface with
 *          the PowerButton soft-switching subsystem. 
 * @author  Jack Lambert, 2022.05.09 */
void PowerButton_Init(void);

//------------------------------------------------------------------------------
/**
  @Summary
    Initializes the CCP3

  @Description
    This routine initializes the CCP3_Initialize.
    This routine must be called before any other CCP3 routine is called.
    This routine should only be called once during system initialization.

  @Preconditions
    None

  @Param
    None

  @Returns
    None
 */
void CCP3_Initialize(void);

//------------------------------------------------------------------------------
/**
  @Summary
    Implements ISR

  @Description
    This routine is used to implement the ISR for the interrupt-driven
    implementations.

  @Returns
    None

  @Param
    None
 */
void CCP3_CaptureISR(void);

//------------------------------------------------------------------------------
/**
  @Summary
    Setter for CCP3 CallBack function

  @Description
    Calling this function will set a new custom call back function that will be 
    called from the Capture ISR.

  @Preconditions
    Initialize the CCP3 module with interrupt before calling this function.

  @Param
    A pointer to the new function

  @Returns
    None
 */
void CCP3_SetCallBack(void (*customCallBack)(uint16_t));

//------------------------------------------------------------------------------

#endif /* POWERBUTTON_H */

//==============================================================================
//--------------------------------END OF FILE-----------------------------------
//==============================================================================
