/* 
 * File:    PowerButton.h
 * Author:  Jack Lambert     <joalambe@ucsc.edu>
 * Project: WCSA_SDP_2022
 *
 * NOTE: CCP3 code originally generated by Microchip Code Configurator (MCC) 
 *       and then further modified by Jack Lambert.
 *       PowerButton implementations were written from scratch.
 * 
 * Created on May 8, 2022, 5:00 PM
 */
//------------------------------------------------------------------------------

#ifndef POWERBUTTON_H
#define	POWERBUTTON_H

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>


//==============================================================================
//------------------------------ PUBLIC LIBRARY --------------------------------
//==============================================================================
/**
 * @funct   PowerButton_Init()
 * @param   None
 * @return  None
 * @brief   Initializes the CCP3 (pin[RA2]) to interface with
 *          the PowerButton soft-switching subsystem. 
 * @author  Jack Lambert, 2022.05.09 */
void PowerButton_Init(void);

//------------------------------------------------------------------------------
/**
 * @funct   PowerButton_ForceShutdown()
 * @param   None
 * @return  None
 * @brief   Reconfigures RA2 as an OUTPUT, drives RA2 LOW, and then blocks CPU
 * @author  Jack Lambert, 2022.05.09 */
void PowerButton_ForceShutdown(void) ;

//------------------------------------------------------------------------------
/**
 * @funct   PowerButton_ForceShutdown()
 * @param   None
 * @return  None
 * @brief   TRUE if power button was pressed. FALSE if not.
 * @author  Jack Lambert, 2022.05.09 */
uint8_t PowerButton_WasBtnPressed(void);

//------------------------------------------------------------------------------
/**
  @Summary
    Initializes the CCP3

  @Description
    This routine initializes the CCP3_Initialize.
    This routine must be called before any other CCP3 routine is called.
    This routine should only be called once during system initialization.

  @Preconditions
    None

  @Param
    None

  @Returns
    None
 */
void CCP3_Initialize(void);

//------------------------------------------------------------------------------
/**
  @Summary
    Implements ISR

  @Description
    This routine is used to implement the ISR for the interrupt-driven
    implementations.

  @Returns
    None

  @Param
    None
 */
void CCP3_CaptureISR(void);

//------------------------------------------------------------------------------

#endif /* POWERBUTTON_H */

//==============================================================================
//--------------------------------END OF FILE-----------------------------------
//==============================================================================
